[features]
seeds = false
skip-lint = false

[programs.localnet]
pdas = "CvQiLMVDewjGsCycxUwz8bN86b5R7iuFwnsq7yeC23z9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/imalice/.config/solana/id.json"

[scripts]
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.ts"
redeem = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/redeem.ts"
